[package]
name = "labirintus"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }